# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
   hooks:
     # you may remove this if you don't need go generate
     - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
- goos:
  - windows
  - darwin
  - linux
archive:
  replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
